name: Build Arch Package

on:
    push:
        tags:
            - "v*"
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        container:
            image: archlinux:latest

        steps:
            - name: Install system dependencies
              run: |
                  pacman -Syu --noconfirm
                  pacman -S --noconfirm base-devel git sudo pacman-contrib

            - name: Create build user
              run: |
                  useradd -m builder
                  echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

            - name: Checkout repository
              uses: actions/checkout@v6
              with:
                  ref: main
                  fetch-depth: 0 # needed for pushing commits

            - name: Prepare PKGBUILD (version, checksums, SRCINFO)
              run: |
                  TAG="${GITHUB_REF_NAME}"
                  VERSION="${TAG#v}"

                  echo "Tag: $TAG"
                  echo "Version: $VERSION"

                  sed -i "s/^pkgver=.*/pkgver=${VERSION}/" PKGBUILD
                  sed -i "s/^pkgrel=.*/pkgrel=1/" PKGBUILD

                  chown -R builder:builder .

                  sudo -u builder bash -c "
                    cd $PWD
                    sleep 5
                    updpkgsums
                    makepkg --printsrcinfo > .SRCINFO
                  "

            - name: Mark repo as safe for git
              run: |
                  git config --global --add safe.directory "$GITHUB_WORKSPACE"

            - name: Commit updated PKGBUILD and .SRCINFO
              uses: EndBug/add-and-commit@v9
              with:
                  add: "PKGBUILD"
                  message: "ci: bump version to ${{ github.ref_name }}"
                  default_author: github_actions
                  push: origin main

            - name: Prepare clean build dir
              run: |
                  mkdir -p /build
                  cp PKGBUILD /build
                  chown -R builder:builder /build

            - name: Build package
              run: |
                  sudo -u builder bash -c "
                    cd /build
                    makepkg -s --noconfirm --cleanbuild
                  "

            - name: Upload artifact (CI)
              uses: actions/upload-artifact@v7
              with:
                  name: arch-package
                  path: "/build/*.pkg.tar.zst"

            - name: Create GitHub Release and upload package
              uses: softprops/action-gh-release@v3
              with:
                  files: "/build/*.pkg.tar.zst"
